name: EsLint & StyleLint & Prettier

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install or get cached dependencies
        uses: bahmutov/npm-install@v1
      - run: npm run format
      - run: npm run lint:js
      - run: npm run lint:style
