name: Unit tests & Cypress

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run test
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:8080/
