name: Unit tests & Cypress

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:8080/
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint:style
