# Trigger the workflow on push (only for the master branch) or pull request
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          serve-prod-build: npm run serve-prod-build
          wait-on: http://localhost:8080/
